### ISSUE TITLE
Connect to existing REPL (as when using tmux)

### ISSUE THREAD

**Issue by karljs** [idris-hackers/idris-vim#17]
My ideal workflow would involve having the Idris REPL running in one tmux window and Vim running in another.  When I do this and reload the file in Vim it seems to start its own internal REPL somehow which is in no way connected to the existing one.

Is there a way to force Vim to connect to the existing REPL?

**Comment by LeifW** [comment]
The idris repl listens for repl commands on a network port; all the vim mode does is send commands to that port (where hopefully there's a repl listening), via `idris --client 'foo'`.
