### ISSUE TITLE
Odd <LocalLeader>d Behavior

### ISSUE THREAD

**Issue by DavidHarrison** [idris-hackers/idris-vim#32]
The use of \<LocalLeader\>d on `keyNotInLeaf'` fills in `decEq x1 x2 = ?DecEq_rhs_1` in the following code:

```
data Tree : Type -> Type where
  Node : v -> Tree v -> Tree v -> Tree v
  Leaf : Tree v

Map : Type -> Type -> Type
Map k v = Tree (k,v)

data KeyInMap : DecEq key => key -> Map key value -> Type where
  Here  : DecEq key => (k = k') -> KeyInMap k (Node (k',v) l r)
  Left  : DecEq key => KeyInMap k l -> KeyInMap k (Node v l r)
  Right : DecEq key => KeyInMap k r -> KeyInMap k (Node v l r)

keyNotInLeaf' : DecEq key => (m = Leaf) -> KeyInMap k m -> Void
                    decEq x1 x2 = ?DecEq_rhs_1
```

Thanks,
David Harrison

**Comment by xoltar** [comment]
I'm seeing the same issue. This is what happens when hitting <LocalLeader>d on plus':

    data Nat' = Z' | S' Nat'                                                           
                                                                                   
    %name Nat' j,k                                                                     
                                                                                   
    plus' : Nat' -> Nat' -> Nat'                                                       
            Nat j k = ?Nat_rhs

**Comment by raichoo** [comment]
Should be fixed now.

**Comment by srenatus** [comment]
[Seems so, let's close this?](https://asciinema.org/a/0kzmm5ex21zzhvbiyz8jdsb09)
