### ISSUE TITLE
Idris not started?

### ISSUE THREAD

**Issue by NobbZ** [idris-hackers/idris-vim#34]
It seems that idris is not beeing started by vim. Instead I get `Uncaught error: connet: dies not exist (Connection refused)` whenever I try to use one of the idris-mode commands

**Comment by LeifW** [comment]
Yes, it doesn't fork an external process for you currently. My normal workflow is to run `idris Foo.idr` to load the repl on `Foo.idr`, and then use the `:e` command from the repl to launch the editor on that file. But really the only requirement is that an Idris repl be running in the same directory as the file you're editing.
Perhaps some work could be done using new vim (or neovim) features for forking external processes to make it work more like the emacs mode, and take care launching Idris for you?
https://github.com/neovim/neovim/pull/475

**Comment by NobbZ** [comment]
If it is enough to start a repl in the same folder, then I can do it
manually. In Haskell exactly that is part of my workflow, a terminal with
repl and one with the editor, side by side.
Am 03.03.2015 19:21 schrieb "Leif Warner" <notifications@github.com>:

**Comment by LeifW** [comment]
I just checked; apparently it's no longer a requirement that the Idris repl be in the same directory as the files you're working on. I guess idris-vim sends the repl the full pathname when it asks it to load a file? You just need an Idris repl running somewhere on your system (it binds to a network port).

**Comment by NobbZ** [comment]
I just checked it, it works!

I think there should be a note in the readme about this.
