### ISSUE TITLE
<LocalLeader>t resets cursor location to beginning of line

### ISSUE THREAD

**Issue by LeifW** [idris-hackers/idris-vim#35]
Example:

``` idris
blah : a -> a
blah x = ?foo
```

Typing `\t` on `foo` resets the cursor location to the start of the line, the `b` in `blah`.

**Comment by srenatus** [comment]
I've tried reproducing this with `master`, and failed: [screencast](https://asciinema.org/a/5dmie2vd9n39ez8oxqud25vma) (where I keep doing `<LocalLeader>t` in different parts of the line).

**Comment by dkasak** [comment]
This happens for me too with the latest master.

**Comment by eraserhd** [comment]
This happens for me with neovim.

**Comment by dkasak** [comment]
FWIW, I'm using neovim too.
