### ISSUE TITLE
How do you change the syntax coloring?

### ISSUE THREAD

**Issue by danielbarter** [idris-hackers/idris-vim#47]
Hi,

This is a dumb question, but I can't see where the syntax colors are chosen in the source and I want to change them.

How do I do that?

**Comment by srenatus** [comment]
Hi,

this plugin doesn't define colors, it defines _syntax elements_ ([see here](http://vim.wikia.com/wiki/Creating_your_own_syntax_files#Keyword.2C_match_and_region_elements)), [for example](
https://github.com/idris-hackers/idris-vim/blob/master/syntax/idris.vim#L18):

```
syn keyword idrisImport import
```

This teaches vim that `import` is a keyword for Idris imports, and [further down](https://github.com/idris-hackers/idris-vim/blob/master/syntax/idris.vim#L55) we find

```
highlight def link idrisImport Structure
```

which tells vim to highlight (i.e. colour) it as a "Structure" element ([see here](http://vim.wikia.com/wiki/Creating_your_own_syntax_files#Telling_Vim_how_to_highlight_.2B_final_touches)). This is where your colorscheme comes in, defining how vim shows Structure elements.

So to change the way Idris code is coloured, you could change the mapping of syntax elements to highlight options.

HTH :)

**Comment by LeifW** [comment]
Is that a good enough answer? Can this issue be closed? Perhaps we should add that answer to the README or the wiki for this?

**Comment by stephen-smith** [comment]
Migrated to the wiki.  I also vote to close the issue.
