### ISSUE TITLE
strip ? from hole name before passing  it to idris?

### ISSUE THREAD

**Issue by pacak** [idris-hackers/idris-vim#74]
It seems like in order to make lemmas and some other  things to work we need to cut of ?.
```
  if word =~ '^?'
    " Cut off '?' that introduces a hole identifier.
    let word = strpart(word, 1)
  endif
```
Before \l on hole dies with "invalid command":
```
plus_commutes Z m = ?plus_commutes_rhs_4
```

After above mentioned snippet is added \l produces

```
plus_commutes_rhs_4 : m = plus m 0
```

**Comment by dkasak** [comment]
Isn't this already done in #71?

**Comment by pacak** [comment]
You right. I cloned the repo before 74 was merged. It took some time to
figure out the problem. This issue can be closed.
