### ISSUE TITLE
Unable to connect to a running Idris repl 

### ISSUE THREAD

**Issue by pe200012** [idris-hackers/idris-vim#82]
The funcionality is broken. Whenver I send a conmmand, the message shows up.
<pre>Unable to connect to a running Idris repl </pre>
I built idris from source (using stack), does it cause the problem?

**Comment by zenntenn** [comment]
You need to have an instance of Idris running for idris-vim to connect to it.

**Comment by pe200012** [comment]
It did solve the problem...
I think it would be better if it behaves like how Merlin behaves.
Anyway, thank you.
