### ISSUE TITLE
Unable to connect to a running idris repl

### ISSUE THREAD

**Issue by ivanperez-keera** [idris-hackers/idris-vim#84]
Hi

I'm getting this in Ubuntu (16.04 and 17.10).

I have `pathogen` installed and set up in my `.vimrc`, I installed `idris-vim`, I started `idris --ide-mode`, `idris` is in my current `PATH`, and yet this happens. The same happens if I used a console and run `idris --client`.

Perhaps someone could, please, add the instructions for any novice vim user to get this to work, from a fresh vim installation?

**Comment by ivanperez-keera** [comment]
Found the solution.

**Comment by danbroooks** [comment]
What did you do to resolve this @ivanperez-keera ?

I am currently having the same issue (Ubuntu 16.04), I'm getting `Unable to connect to a running Idris repl` in `vim`, and the same when I run `idris --client 1`. I've got `idris --ide-mode` running in another terminal window.

**Comment by danbroooks** [comment]
I've managed to get this working, I was opening `vim` on it's own and trying to run the commands that way, to get `idris-vim` working I opened the file via `idris` (ie `idris src/Main.idr`) and then doing `:e` in the REPL

**Comment by ivanperez-keera** [comment]
I think my issue was that I had installed idris in a sandbox so I had to use `cabal exec -- idris <args>`.
